version: "3"

services:

  postgres:
    image: postgres:14.3
    container_name: postgres
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mlflow
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    ports:
      - 5432:5432
    hostname: postgres
    restart: always
    stdin_open: true

  mlflow:
    build:
      context: datapipeline
      dockerfile: Dockerfile.mlflow
    volumes:
      - ./mlartifacts:/opt/outputs/mlartifacts
      - ./mlruns:/opt/outputs/mlruns
    ports:
      - 5000:5000
    networks:
      - backend
    command:
      - "mlflow"
      - "server"
      - "--backend-store-uri"
      - "postgresql+psycopg2://postgres:password@postgres:5432/mlflow"
      - "--default-artifact-root"
      - "/opt/outputs/mlruns"
      - "--host"
      - "0.0.0.0"

  dashboard:
    build:
      context: bi
    volumes:
      - ./data_storage:/data_storage
    ports:
      - 8501:8501
    networks:
      - backend
    command:
      - "poetry"
      - "run"
      - "streamlit"
      - "run"
      - "src/main.py"

  datapipeline:
    build:
      context: datapipeline
    volumes:
      - ./data_storage:/data_storage
      - ./mlartifacts/:/mlartifacts
    ports:
      - 8000:8000
    networks:
      - backend
    command:
      - "poetry"
      - "run"
      - "python3"
      - "app.py"

networks:
  backend: