name: build and upload to ncloud object storage

on:
  push:
    branches:
      - main


jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List files in the directory
      run: ls -la

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Compose services
      run: |
        docker-compose build
        docker-compose images -q > images.txt
    
    - name: Save Docker images as tar files
      run: |
        mkdir -p docker_images
        while IFS= read -r image_id; do
          image_name=$(docker image inspect --format '{{.Config.Image}}' $image_id)
          docker save -o docker_images/${image_name}.tar $image_id
        done < images.txt

  