name: connect to ncloud and upload

on:
  push:
    branches:
      - main


jobs:
  
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Compose services
      run: |
        docker-compose build
        docker-compose images -q > images.txt
    
    - name: Save Docker images as tar files
      run: |
        sh zip-docker-compose.sh
    
    
    - name: Install Aws-CLI(ncloud는 aws-cli를 사용한다.)
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: configure ncloud
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.NCP_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.NCP_PASSWORD }}
      run: |
        echo "Access Key ID: $AWS_ACCESS_KEY_ID"  # For debugging
        echo "Secret Access Key: $AWS_SECRET_ACCESS_KEY"  # For debugging
        aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
        aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
        aws configure set default.region ap-northeast-2

    - name: upload random file

      run: |
        aws --endpoint-url=https://kr.object.fin-ncloudstorage.com \
        s3 cp docker_project.zip s3://petfins/petfins-ml-deploy-pipeline/docker_project.zip --recursive
        
      